import { Block } from 'payload'

export const Hero: Block = {
  slug: 'hero',
  labels: {
    singular: 'Hero блок',
    plural: 'Hero блоки',
  },
  fields: [
    {
      name: 'backgroundColor',
      type: 'select',
      label: 'Цвет фона',
      defaultValue: '#ffffff',
      required: true,
      options: [
        { label: 'White', value: '#ffffff' },
        { label: 'Slate 50', value: '#f8fafc' },
        { label: 'Slate 500', value: '#64748b' },
        { label: 'Gray 50', value: '#f9fafb' },
        { label: 'Gray 500', value: '#6b7280' },
        { label: 'Zinc 50', value: '#fafafa' },
        { label: 'Zinc 500', value: '#71717a' },
        { label: 'Neutral 500', value: '#737373' },
        { label: 'Stone 50', value: '#fafaf9' },
        { label: 'Stone 500', value: '#78716c' },
        { label: 'Red 50', value: '#fef2f2' },
        { label: 'Red 500', value: '#ef4444' },
        { label: 'Orange 50', value: '#fff7ed' },
        { label: 'Orange 500', value: '#f97316' },
        { label: 'Amber 50', value: '#fffbeb' },
        { label: 'Amber 500', value: '#f59e0b' },
        { label: 'Yellow 50', value: '#fefce8' },
        { label: 'Yellow 500', value: '#eab308' },
        { label: 'Lime 50', value: '#f7fee7' },
        { label: 'Lime 500', value: '#84cc16' },
        { label: 'Green 50', value: '#f0fdf4' },
        { label: 'Green 500', value: '#22c55e' },
        { label: 'Emerald 50', value: '#ecfdf5' },
        { label: 'Emerald 500', value: '#10b981' },
        { label: 'Teal 50', value: '#f0fdfa' },
        { label: 'Teal 500', value: '#14b8a6' },
        { label: 'Cyan 50', value: '#ecfeff' },
        { label: 'Cyan 500', value: '#06b6d4' },
        { label: 'Sky 50', value: '#f0f9ff' },
        { label: 'Sky 500', value: '#0ea5e9' },
        { label: 'Blue 50', value: '#eff6ff' },
        { label: 'Blue 500', value: '#3b82f6' },
        { label: 'Indigo 50', value: '#eef2ff' },
        { label: 'Indigo 500', value: '#6366f1' },
        { label: 'Violet 50', value: '#f5f3ff' },
        { label: 'Violet 500', value: '#8b5cf6' },
        { label: 'Purple 50', value: '#faf5ff' },
        { label: 'Purple 500', value: '#a855f7' },
        { label: 'Fuchsia 50', value: '#fdf4ff' },
        { label: 'Fuchsia 500', value: '#d946ef' },
        { label: 'Pink 50', value: '#fdf2f8' },
        { label: 'Pink 500', value: '#ec4899' },
        { label: 'Rose 50', value: '#fff1f2' },
        { label: 'Rose 500', value: '#f43f5f' },
      ],
      admin: {
        description: 'Выберите цвет фона из палитры Tailwind',
      },
    },
    {
      name: 'textColor',
      type: 'select',
      label: 'Цвет текста',
      defaultValue: 'foreground',
      required: true,
      options: [
        { label: 'Foreground (темный)', value: 'foreground' },
        { label: 'Background (светлый)', value: 'background' },
      ],
      admin: {
        description: 'Выберите цвет для заголовка и описания',
      },
    },
    {
      name: 'title',
      type: 'text',
      label: 'Заголовок',
      required: true,
    },
    {
      name: 'description',
      type: 'textarea',
      label: 'Описание',
      required: true,
    },
    {
      name: 'image',
      type: 'upload',
      label: 'Картинка',
      relationTo: 'media',
      required: true,
    },
    {
      name: 'button',
      type: 'group',
      label: 'Кнопка',
      fields: [
        {
          name: 'text',
          type: 'text',
          label: 'Текст кнопки',
          required: true,
          defaultValue: 'Узнать больше',
        },
        {
          name: 'url',
          type: 'text',
          label: 'Ссылка',
          required: true,
          defaultValue: '#',
        },
        {
          name: 'variant',
          type: 'select',
          label: 'Вариант стиля',
          required: true,
          defaultValue: 'default',
          options: [
            {
              label: 'Default',
              value: 'default',
            },
            {
              label: 'Destructive',
              value: 'destructive',
            },
            {
              label: 'Outline',
              value: 'outline',
            },
            {
              label: 'Secondary',
              value: 'secondary',
            },
            {
              label: 'Ghost',
              value: 'ghost',
            },
            {
              label: 'Link',
              value: 'link',
            },
          ],
        },
        {
          name: 'customColor',
          type: 'text',
          label: 'Пользовательский цвет фона (HEX)',
          admin: {
            description: 'Оставьте пустым для использования стандартного цвета варианта',
            placeholder: '#000000',
          },
        },
        {
          name: 'textColor',
          type: 'text',
          label: 'Цвет текста кнопки (HEX)',
          defaultValue: '#ffffff',
          admin: {
            description: 'Цвет текста на кнопке (например: #ffffff для белого)',
            placeholder: '#ffffff',
          },
        },
        {
          name: 'icon',
          type: 'select',
          label: 'Иконка справа от текста',
          admin: {
            description: 'Выберите иконку, которая будет отображаться справа от текста кнопки',
          },
          options: [
            { label: 'Без иконки', value: '' },
            // Стрелки
            { label: '→ Стрелка вправо', value: 'ArrowRight' },
            { label: '↗ Стрелка вверх-вправо', value: 'ArrowUpRight' },
            { label: '↘ Стрелка вниз-вправо', value: 'ArrowDownRight' },
            { label: '← Стрелка влево', value: 'ArrowLeft' },
            { label: '↑ Стрелка вверх', value: 'ArrowUp' },
            { label: '↓ Стрелка вниз', value: 'ArrowDown' },
            { label: '⟩ Шеврон вправо', value: 'ChevronRight' },
            { label: '⟩⟩ Шевроны вправо', value: 'ChevronsRight' },
            { label: '⟨ Шеврон влево', value: 'ChevronLeft' },
            { label: '∧ Шеврон вверх', value: 'ChevronUp' },
            { label: '∨ Шеврон вниз', value: 'ChevronDown' },
            { label: '↻ Обновить', value: 'RefreshCw' },
            { label: '⤴ Поделиться', value: 'Share' },
            { label: '⤵ Переход', value: 'MoveRight' },
            // Действия
            { label: '⬇ Скачать', value: 'Download' },
            { label: '⬆ Загрузить', value: 'Upload' },
            { label: '✉ Отправить', value: 'Send' },
            { label: '▶ Плей', value: 'Play' },
            { label: '+ Плюс', value: 'Plus' },
            { label: '✓ Проверка', value: 'Check' },
            { label: '✓✓ Двойная проверка', value: 'CheckCheck' },
            { label: '× Закрыть', value: 'X' },
            { label: '⊕ Плюс в кружке', value: 'PlusCircle' },
            { label: '⊖ Минус в кружке', value: 'MinusCircle' },
            { label: '👁 Глаз', value: 'Eye' },
            { label: '🔒 Замок', value: 'Lock' },
            { label: '🔓 Открытый замок', value: 'Unlock' },
            // Бизнес и покупки
            { label: '🛒 Корзина', value: 'ShoppingCart' },
            { label: '🛍 Сумка', value: 'ShoppingBag' },
            { label: '💳 Кредитная карта', value: 'CreditCard' },
            { label: '💰 Деньги', value: 'DollarSign' },
            { label: '🎁 Подарок', value: 'Gift' },
            { label: '🏷 Ярлык', value: 'Tag' },
            { label: '% Процент', value: 'Percent' },
            // Коммуникация
            { label: '✉ Почта', value: 'Mail' },
            { label: '💬 Сообщение', value: 'MessageCircle' },
            { label: '📞 Телефон', value: 'Phone' },
            { label: '📹 Видео', value: 'Video' },
            { label: '🔔 Колокольчик', value: 'Bell' },
            { label: '💬 Чат', value: 'MessageSquare' },
            // Медиа и файлы
            { label: '📄 Файл', value: 'File' },
            { label: '📁 Папка', value: 'Folder' },
            { label: '🖼 Картинка', value: 'Image' },
            { label: '📎 Скрепка', value: 'Paperclip' },
            { label: '🔗 Ссылка', value: 'Link' },
            { label: '🌐 Внешняя ссылка', value: 'ExternalLink' },
            { label: '🔍 Поиск', value: 'Search' },
            { label: '🔍+ Увеличить поиск', value: 'ZoomIn' },
            // Интерфейс
            { label: '⚙ Настройки', value: 'Settings' },
            { label: 'ℹ Информация', value: 'Info' },
            { label: '❓ Вопрос', value: 'HelpCircle' },
            { label: '⚠ Предупреждение', value: 'AlertTriangle' },
            { label: '⚠ Круг предупреждения', value: 'AlertCircle' },
            { label: '👤 Пользователь', value: 'User' },
            { label: '👥 Пользователи', value: 'Users' },
            { label: '🏠 Дом', value: 'Home' },
            { label: '📍 Местоположение', value: 'MapPin' },
            { label: '🌍 Глобус', value: 'Globe' },
            // Время и календарь
            { label: '📅 Календарь', value: 'Calendar' },
            { label: '⏰ Часы', value: 'Clock' },
            { label: '⏱ Таймер', value: 'Timer' },
            { label: '⌚ Часы-круг', value: 'Clock3' },
            // Социальные и другие
            { label: '⭐ Звезда', value: 'Star' },
            { label: '❤ Сердце', value: 'Heart' },
            { label: '👍 Палец вверх', value: 'ThumbsUp' },
            { label: '👎 Палец вниз', value: 'ThumbsDown' },
            { label: '🔖 Закладка', value: 'Bookmark' },
            { label: '🎯 Цель', value: 'Target' },
            { label: '🏆 Трофей', value: 'Trophy' },
            { label: '⚡ Молния', value: 'Zap' },
            { label: '🚀 Ракета', value: 'Rocket' },
            { label: '✨ Искры', value: 'Sparkles' },
          ],
        },
      ],
    },
  ],
}

