import { GlobalConfig } from 'payload'

export const Settings: GlobalConfig = {
  slug: 'settings',
  label: 'Настройки сайта',
  access: {
    read: () => true, // Публичный доступ для чтения
  },
  fields: [
    {
      type: 'tabs',
      tabs: [
        {
          label: 'Основное',
          fields: [
            {
              name: 'logo',
              type: 'upload',
              label: 'Логотип',
              relationTo: 'media',
              required: false,
            },
            {
              name: 'title',
              type: 'text',
              label: 'Заголовок (Title)',
              required: false,
              defaultValue: 'IWA360',
            },
            {
              name: 'description',
              type: 'textarea',
              label: 'Описание (Description)',
              required: false,
              defaultValue: 'Добро пожаловать на наш сайт',
            },
          ],
        },
        {
          label: 'Меню',
          fields: [
            {
              name: 'menuLogo',
              type: 'upload',
              label: 'Логотип в меню',
              relationTo: 'media',
              required: false,
              admin: {
                description: 'Логотип, который будет отображаться в шапке сайта',
              },
            },
            {
              name: 'mainMenu',
              type: 'array',
              label: 'Главное меню',
              admin: {
                description: 'Основные пункты меню (слева)',
              },
              fields: [
                {
                  name: 'type',
                  type: 'select',
                  label: 'Тип пункта',
                  required: true,
                  defaultValue: 'link',
                  options: [
                    {
                      label: 'Обычная ссылка',
                      value: 'link',
                    },
                    {
                      label: 'Выпадающее меню',
                      value: 'dropdown',
                    },
                  ],
                },
                {
                  name: 'label',
                  type: 'text',
                  label: 'Название',
                  required: true,
                },
                {
                  name: 'url',
                  type: 'text',
                  label: 'Ссылка',
                  required: false,
                  admin: {
                    description: 'Для обычной ссылки (например: /about)',
                  },
                },
                {
                  name: 'activeTextColor',
                  type: 'select',
                  label: 'Цвет текста (активное состояние)',
                  required: false,
                  admin: {
                    description: 'Цвет текста когда пункт меню активен. По умолчанию: Primary',
                  },
                  options: [
                    { label: 'По умолчанию (Primary)', value: '' },
                    { label: 'Primary 50', value: '#E0F7F2' },
                    { label: 'Primary 500', value: '#00B08B' },
                    { label: 'White', value: '#ffffff' },
                    { label: 'Slate 50', value: '#f8fafc' },
                    { label: 'Slate 500', value: '#64748b' },
                    { label: 'Gray 50', value: '#f9fafb' },
                    { label: 'Gray 500', value: '#6b7280' },
                    { label: 'Zinc 50', value: '#fafafa' },
                    { label: 'Zinc 500', value: '#71717a' },
                    { label: 'Neutral 500', value: '#737373' },
                    { label: 'Stone 50', value: '#fafaf9' },
                    { label: 'Stone 500', value: '#78716c' },
                    { label: 'Red 50', value: '#fef2f2' },
                    { label: 'Red 500', value: '#ef4444' },
                    { label: 'Orange 50', value: '#fff7ed' },
                    { label: 'Orange 500', value: '#f97316' },
                    { label: 'Amber 50', value: '#fffbeb' },
                    { label: 'Amber 500', value: '#f59e0b' },
                    { label: 'Yellow 50', value: '#fefce8' },
                    { label: 'Yellow 500', value: '#eab308' },
                    { label: 'Lime 50', value: '#f7fee7' },
                    { label: 'Lime 500', value: '#84cc16' },
                    { label: 'Green 50', value: '#f0fdf4' },
                    { label: 'Green 500', value: '#22c55e' },
                    { label: 'Emerald 50', value: '#ecfdf5' },
                    { label: 'Emerald 500', value: '#10b981' },
                    { label: 'Teal 50', value: '#f0fdfa' },
                    { label: 'Teal 500', value: '#14b8a6' },
                    { label: 'Cyan 50', value: '#ecfeff' },
                    { label: 'Cyan 500', value: '#06b6d4' },
                    { label: 'Sky 50', value: '#f0f9ff' },
                    { label: 'Sky 500', value: '#0ea5e9' },
                    { label: 'Blue 50', value: '#eff6ff' },
                    { label: 'Blue 500', value: '#3b82f6' },
                    { label: 'Indigo 50', value: '#eef2ff' },
                    { label: 'Indigo 500', value: '#6366f1' },
                    { label: 'Violet 50', value: '#f5f3ff' },
                    { label: 'Violet 500', value: '#8b5cf6' },
                    { label: 'Purple 50', value: '#faf5ff' },
                    { label: 'Purple 500', value: '#a855f7' },
                    { label: 'Fuchsia 50', value: '#fdf4ff' },
                    { label: 'Fuchsia 500', value: '#d946ef' },
                    { label: 'Pink 50', value: '#fdf2f8' },
                    { label: 'Pink 500', value: '#ec4899' },
                    { label: 'Rose 50', value: '#fff1f2' },
                    { label: 'Rose 500', value: '#f43f5f' },
                  ],
                },
                {
                  name: 'activeBorderColor',
                  type: 'select',
                  label: 'Цвет бордера (активное состояние)',
                  required: false,
                  admin: {
                    description: 'Цвет нижнего бордера когда пункт меню активен. По умолчанию: Primary',
                  },
                  options: [
                    { label: 'По умолчанию (Primary)', value: '' },
                    { label: 'Primary 50', value: '#E0F7F2' },
                    { label: 'Primary 500', value: '#00B08B' },
                    { label: 'White', value: '#ffffff' },
                    { label: 'Slate 50', value: '#f8fafc' },
                    { label: 'Slate 500', value: '#64748b' },
                    { label: 'Gray 50', value: '#f9fafb' },
                    { label: 'Gray 500', value: '#6b7280' },
                    { label: 'Zinc 50', value: '#fafafa' },
                    { label: 'Zinc 500', value: '#71717a' },
                    { label: 'Neutral 500', value: '#737373' },
                    { label: 'Stone 50', value: '#fafaf9' },
                    { label: 'Stone 500', value: '#78716c' },
                    { label: 'Red 50', value: '#fef2f2' },
                    { label: 'Red 500', value: '#ef4444' },
                    { label: 'Orange 50', value: '#fff7ed' },
                    { label: 'Orange 500', value: '#f97316' },
                    { label: 'Amber 50', value: '#fffbeb' },
                    { label: 'Amber 500', value: '#f59e0b' },
                    { label: 'Yellow 50', value: '#fefce8' },
                    { label: 'Yellow 500', value: '#eab308' },
                    { label: 'Lime 50', value: '#f7fee7' },
                    { label: 'Lime 500', value: '#84cc16' },
                    { label: 'Green 50', value: '#f0fdf4' },
                    { label: 'Green 500', value: '#22c55e' },
                    { label: 'Emerald 50', value: '#ecfdf5' },
                    { label: 'Emerald 500', value: '#10b981' },
                    { label: 'Teal 50', value: '#f0fdfa' },
                    { label: 'Teal 500', value: '#14b8a6' },
                    { label: 'Cyan 50', value: '#ecfeff' },
                    { label: 'Cyan 500', value: '#06b6d4' },
                    { label: 'Sky 50', value: '#f0f9ff' },
                    { label: 'Sky 500', value: '#0ea5e9' },
                    { label: 'Blue 50', value: '#eff6ff' },
                    { label: 'Blue 500', value: '#3b82f6' },
                    { label: 'Indigo 50', value: '#eef2ff' },
                    { label: 'Indigo 500', value: '#6366f1' },
                    { label: 'Violet 50', value: '#f5f3ff' },
                    { label: 'Violet 500', value: '#8b5cf6' },
                    { label: 'Purple 50', value: '#faf5ff' },
                    { label: 'Purple 500', value: '#a855f7' },
                    { label: 'Fuchsia 50', value: '#fdf4ff' },
                    { label: 'Fuchsia 500', value: '#d946ef' },
                    { label: 'Pink 50', value: '#fdf2f8' },
                    { label: 'Pink 500', value: '#ec4899' },
                    { label: 'Rose 50', value: '#fff1f2' },
                    { label: 'Rose 500', value: '#f43f5f' },
                  ],
                },
                {
                  name: 'dropdownItems',
                  type: 'array',
                  label: 'Пункты выпадающего меню',
                  fields: [
                    {
                      name: 'label',
                      type: 'text',
                      label: 'Название',
                      required: true,
                    },
                    {
                      name: 'url',
                      type: 'text',
                      label: 'Ссылка',
                      required: true,
                    },
                    {
                      name: 'icon',
                      type: 'upload',
                      label: 'Иконка/Картинка',
                      relationTo: 'media',
                      required: false,
                    },
                    {
                      name: 'description',
                      type: 'text',
                      label: 'Описание',
                      required: false,
                    },
                    {
                      name: 'activeTextColor',
                      type: 'select',
                      label: 'Цвет текста (активное состояние)',
                      required: false,
                      admin: {
                        description: 'Цвет текста когда пункт меню активен. По умолчанию: Primary',
                      },
                      options: [
                        { label: 'По умолчанию (Primary)', value: '' },
                        { label: 'Primary 50', value: '#E0F7F2' },
                        { label: 'Primary 500', value: '#00B08B' },
                        { label: 'White', value: '#ffffff' },
                        { label: 'Slate 50', value: '#f8fafc' },
                        { label: 'Slate 500', value: '#64748b' },
                        { label: 'Gray 50', value: '#f9fafb' },
                        { label: 'Gray 500', value: '#6b7280' },
                        { label: 'Zinc 50', value: '#fafafa' },
                        { label: 'Zinc 500', value: '#71717a' },
                        { label: 'Neutral 500', value: '#737373' },
                        { label: 'Stone 50', value: '#fafaf9' },
                        { label: 'Stone 500', value: '#78716c' },
                        { label: 'Red 50', value: '#fef2f2' },
                        { label: 'Red 500', value: '#ef4444' },
                        { label: 'Orange 50', value: '#fff7ed' },
                        { label: 'Orange 500', value: '#f97316' },
                        { label: 'Amber 50', value: '#fffbeb' },
                        { label: 'Amber 500', value: '#f59e0b' },
                        { label: 'Yellow 50', value: '#fefce8' },
                        { label: 'Yellow 500', value: '#eab308' },
                        { label: 'Lime 50', value: '#f7fee7' },
                        { label: 'Lime 500', value: '#84cc16' },
                        { label: 'Green 50', value: '#f0fdf4' },
                        { label: 'Green 500', value: '#22c55e' },
                        { label: 'Emerald 50', value: '#ecfdf5' },
                        { label: 'Emerald 500', value: '#10b981' },
                        { label: 'Teal 50', value: '#f0fdfa' },
                        { label: 'Teal 500', value: '#14b8a6' },
                        { label: 'Cyan 50', value: '#ecfeff' },
                        { label: 'Cyan 500', value: '#06b6d4' },
                        { label: 'Sky 50', value: '#f0f9ff' },
                        { label: 'Sky 500', value: '#0ea5e9' },
                        { label: 'Blue 50', value: '#eff6ff' },
                        { label: 'Blue 500', value: '#3b82f6' },
                        { label: 'Indigo 50', value: '#eef2ff' },
                        { label: 'Indigo 500', value: '#6366f1' },
                        { label: 'Violet 50', value: '#f5f3ff' },
                        { label: 'Violet 500', value: '#8b5cf6' },
                        { label: 'Purple 50', value: '#faf5ff' },
                        { label: 'Purple 500', value: '#a855f7' },
                        { label: 'Fuchsia 50', value: '#fdf4ff' },
                        { label: 'Fuchsia 500', value: '#d946ef' },
                        { label: 'Pink 50', value: '#fdf2f8' },
                        { label: 'Pink 500', value: '#ec4899' },
                        { label: 'Rose 50', value: '#fff1f2' },
                        { label: 'Rose 500', value: '#f43f5f' },
                      ],
                    },
                    {
                      name: 'activeBorderColor',
                      type: 'select',
                      label: 'Цвет бордера (активное состояние)',
                      required: false,
                      admin: {
                        description: 'Цвет нижнего бордера родительского пункта когда этот элемент активен. По умолчанию: Primary',
                      },
                      options: [
                        { label: 'По умолчанию (Primary)', value: '' },
                        { label: 'Primary 50', value: '#E0F7F2' },
                        { label: 'Primary 500', value: '#00B08B' },
                        { label: 'White', value: '#ffffff' },
                        { label: 'Slate 50', value: '#f8fafc' },
                        { label: 'Slate 500', value: '#64748b' },
                        { label: 'Gray 50', value: '#f9fafb' },
                        { label: 'Gray 500', value: '#6b7280' },
                        { label: 'Zinc 50', value: '#fafafa' },
                        { label: 'Zinc 500', value: '#71717a' },
                        { label: 'Neutral 500', value: '#737373' },
                        { label: 'Stone 50', value: '#fafaf9' },
                        { label: 'Stone 500', value: '#78716c' },
                        { label: 'Red 50', value: '#fef2f2' },
                        { label: 'Red 500', value: '#ef4444' },
                        { label: 'Orange 50', value: '#fff7ed' },
                        { label: 'Orange 500', value: '#f97316' },
                        { label: 'Amber 50', value: '#fffbeb' },
                        { label: 'Amber 500', value: '#f59e0b' },
                        { label: 'Yellow 50', value: '#fefce8' },
                        { label: 'Yellow 500', value: '#eab308' },
                        { label: 'Lime 50', value: '#f7fee7' },
                        { label: 'Lime 500', value: '#84cc16' },
                        { label: 'Green 50', value: '#f0fdf4' },
                        { label: 'Green 500', value: '#22c55e' },
                        { label: 'Emerald 50', value: '#ecfdf5' },
                        { label: 'Emerald 500', value: '#10b981' },
                        { label: 'Teal 50', value: '#f0fdfa' },
                        { label: 'Teal 500', value: '#14b8a6' },
                        { label: 'Cyan 50', value: '#ecfeff' },
                        { label: 'Cyan 500', value: '#06b6d4' },
                        { label: 'Sky 50', value: '#f0f9ff' },
                        { label: 'Sky 500', value: '#0ea5e9' },
                        { label: 'Blue 50', value: '#eff6ff' },
                        { label: 'Blue 500', value: '#3b82f6' },
                        { label: 'Indigo 50', value: '#eef2ff' },
                        { label: 'Indigo 500', value: '#6366f1' },
                        { label: 'Violet 50', value: '#f5f3ff' },
                        { label: 'Violet 500', value: '#8b5cf6' },
                        { label: 'Purple 50', value: '#faf5ff' },
                        { label: 'Purple 500', value: '#a855f7' },
                        { label: 'Fuchsia 50', value: '#fdf4ff' },
                        { label: 'Fuchsia 500', value: '#d946ef' },
                        { label: 'Pink 50', value: '#fdf2f8' },
                        { label: 'Pink 500', value: '#ec4899' },
                        { label: 'Rose 50', value: '#fff1f2' },
                        { label: 'Rose 500', value: '#f43f5f' },
                      ],
                    },
                  ],
                },
              ],
            },
            {
              name: 'authMenu',
              type: 'group',
              label: 'Меню авторизации (справа)',
              fields: [
                {
                  name: 'loginButton',
                  type: 'group',
                  label: 'Кнопка "Войти"',
                  fields: [
                    {
                      name: 'label',
                      type: 'text',
                      label: 'Текст кнопки',
                      defaultValue: 'Войти',
                      required: true,
                    },
                    {
                      name: 'url',
                      type: 'text',
                      label: 'Ссылка',
                      defaultValue: '/login',
                      required: true,
                    },
                  ],
                },
                {
                  name: 'registerButton',
                  type: 'group',
                  label: 'Кнопка "Регистрация"',
                  fields: [
                    {
                      name: 'label',
                      type: 'text',
                      label: 'Текст кнопки',
                      defaultValue: 'Регистрация',
                      required: true,
                    },
                    {
                      name: 'url',
                      type: 'text',
                      label: 'Ссылка',
                      defaultValue: '/register',
                      required: true,
                    },
                  ],
                },
              ],
            },
          ],
        },
        {
          label: 'Cookie и согласия',
          description: 'Настройки баннера cookie и текстов согласий',
          fields: [
            {
              name: 'cookieBanner',
              type: 'group',
              label: 'Баннер Cookie',
              fields: [
                {
                  name: 'enabled',
                  type: 'checkbox',
                  label: 'Показывать баннер Cookie',
                  defaultValue: true,
                  admin: {
                    description: 'Включить/выключить баннер о файлах cookie',
                  },
                },
                {
                  name: 'title',
                  type: 'text',
                  label: 'Заголовок',
                  defaultValue: 'Мы используем файлы cookie',
                  required: true,
                  admin: {
                    condition: (data, siblingData) => siblingData?.enabled,
                  },
                },
                {
                  name: 'description',
                  type: 'textarea',
                  label: 'Описание',
                  defaultValue: 'Этот сайт использует файлы cookie для улучшения пользовательского опыта и анализа трафика. Продолжая использовать сайт, вы соглашаетесь с использованием cookie.',
                  required: true,
                  admin: {
                    description: 'Текст в баннере cookie',
                    condition: (data, siblingData) => siblingData?.enabled,
                  },
                },
                {
                  name: 'acceptButtonText',
                  type: 'text',
                  label: 'Текст кнопки согласия',
                  defaultValue: 'Принять',
                  required: true,
                  admin: {
                    condition: (data, siblingData) => siblingData?.enabled,
                  },
                },
                {
                  name: 'policyLinkText',
                  type: 'text',
                  label: 'Текст ссылки на политику',
                  defaultValue: 'Политика конфиденциальности',
                  admin: {
                    description: 'Текст ссылки на страницу политики конфиденциальности',
                    condition: (data, siblingData) => siblingData?.enabled,
                  },
                },
              ],
            },
            {
              name: 'formConsent',
              type: 'group',
              label: 'Текст согласия в формах',
              fields: [
                {
                  name: 'text',
                  type: 'textarea',
                  label: 'Текст согласия',
                  defaultValue: 'Нажимая на кнопку отправить, вы даете согласие на обработку персональных данных и соглашаетесь с политикой конфиденциальности.',
                  required: true,
                  admin: {
                    description: 'Текст, который будет отображаться под формой',
                  },
                },
                {
                  name: 'privacyPolicyText',
                  type: 'text',
                  label: 'Текст ссылки "Политика конфиденциальности"',
                  defaultValue: 'политикой конфиденциальности',
                  required: true,
                },
                {
                  name: 'personalDataText',
                  type: 'text',
                  label: 'Текст ссылки "Обработка персональных данных"',
                  defaultValue: 'обработку персональных данных',
                  required: true,
                },
              ],
            },
          ],
        },
      ],
    },
  ],
}
